from unittest import TestCase

class TestProcessor(TestCase):
    def test_it_works(self):
        self.fail('Prueba fallida intencionalmente')
